### PR TITLE
Restore IE11 compat, fix background, fix focus

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Comment by timja** [comment]
cc @oleg-nenashev @fqueiruga

**Comment by oleg-nenashev** [comment]
Some description would be useful for UI newbies like me

**Comment by timja** [comment]
The IE11 compat was explained by Felix in the other PR, because this css isn’t ran through web pack it needs manual fallbacks for IE11 added

(It could also be refactored to run through webpack instead)

Moving background to body fixes the white background at the bottom and side 

Outline: 0, fixes the weird focus border, it was already set for I believe checkboxes but not for text inputs

**Comment by oleg-nenashev** [comment]
Thanks!

**Pull request merged**
